pipeline {
  agent { label 'linux && docker' }

  environment {
    IMAGE = "docker.io/${DOCKERHUB_USER}/flask-portfolio"
    PYTHON = "python3"
  }

  options { timestamps(); ansiColor('xterm') }

  stages {
    stage('Checkout') { steps { checkout scm } }

    stage('Unit Tests') {
      steps {
        sh """
          ${PYTHON} -m pip install --upgrade pip
          ${PYTHON} -m pip install -r requirements.txt
          pytest -q
        """
      }
    }

    stage('Build Image') {
      steps {
        sh "docker build -f docker/Dockerfile -t ${IMAGE}:${env.GIT_COMMIT} ."
      }
    }

    stage('Login & Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'DH_USER', passwordVariable: 'DH_PASS')]) {
          sh """
            echo "$DH_PASS" | docker login -u "$DH_USER" --password-stdin
            docker push ${IMAGE}:${GIT_COMMIT}
            if [ "${BRANCH_NAME}" = "main" ]; then
              docker tag ${IMAGE}:${GIT_COMMIT} ${IMAGE}:prod
              docker push ${IMAGE}:prod
            fi
          """
        }
      }
    }
  }

  post {
    always {
      sh 'docker image ls | head -n 10 || true'
    }
  }
 